name = "fthduniq-live-site"
main = "worker.js"
compatibility_date = "2026-04-26"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "CAREER_KV"
id = "id = "766e6fb28eb04977a2cded6e3c60ee
